spring:
    datasource:
        url: jdbc:postgresql://ep-lucky-queen-69256101.ap-southeast-1.aws.neon.tech/ptah?user=jarryscript&password=Q0l7YVmgzjaF
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
            minimum-idle: 1
            idle-timeout: 300000
            max-lifetime: 1800000
            pool-name: MyHikariPool
    jpa:
        show-sql: true
        logging:
            level:
                org.hibernate.SQL=DEBUG
                org.hibernate.type=TRACE
    data:
        redis:
            host: apn1-solid-hen-34573.upstash.io
            port: 34573
            password: b16cd1da3d47428e95444567f9faf06c
            timeout: 2000

logging:
    level:
        org.springframework.security: TRACE

security:
    non-secure-paths: /user/login, /user/register, /user/logout, /error

liquibase:
    enabled: true
    datasources:
        default:
            change-log: 'classpath:db/liquibase-changelog.xml'

